### ISSUE TITLE
Unable to fetch PromisesPlugin

### ISSUE THREAD

**Issue by DokuMe** [aerogear/aerogear-cordova-push#135] opened 2019-10-29 23:04 UTC
## Description
When adding android platform i get the following error:
unable to fetch https://github.com/vstirbu/PromisesPlugin.git

## Working solution for me
My solution was to change the dependency in the config.xml of the plugin to:
<dependency id="es6-promise-plugin" version="4.1.0" />

checkout here: https://github.com/vstirbu/PromisesPlugin

## Expected Behavior
aerogear-cordova-push plugin should get installed

## Actual Behavior
no able to install plugin

## Environment

* Operating system: mac os catalina
* Project Versions: cordova 8

**Comment by danielpassos** [comment] 2019-10-30 20:58
Hi @DokuMe I'm trying to reproduce that without success. That is what I'm doing:

**Install Cordova 8**

```bash
$ npm install -g cordova@8
/Users/passos/.nvm/versions/node/v12.12.0/bin/cordova -> /Users/passos/.nvm/versions/node/v12.12.0/lib/node_modules/cordova/bin/cordova
+ cordova@8.1.2
updated 1 package in 2.845s
```
**Check Cordova version**
```bash
$ cordova -v
8.1.2 (cordova-lib@8.1.1)
```
**Create a new Cordova app**
```bash
$ cordova create push-app org.aerogear.playground
Creating a new cordova project.
```

```bash
$ cd push-app
```

**Add a dummy `google-service.json`**
```bash
cat <<EOF >./www/google-services.json
{
  "project_info": {
    "project_number": "123456789012",
    "firebase_url": "https://aerogear.firebaseio.com",
    "project_id": "aerogear",
    "storage_bucket": "aerogear.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:754329551899:android:621420eb6f5bc9df",
        "android_client_info": {
          "package_name": "org.aerogear.playground"
        }
      },
      "oauth_client": [
        {
          "client_id": "9B2B57E6-6672-4672-B11D-63A3D5DD6DFF.apps.googleusercontent.com",
          "client_type": 3
        },
        {
          "client_id": "9B2B57E6-6672-4672-B11D-63A3D5DD6DFF.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "9B2B57E6-6672-4672-B11D-63A3D5DD6DFF"
        }
      ],
      "services": {
        "analytics_service": {
          "status": 1
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 2
        }
      }
    }
  ],
  "configuration_version": "1"
}
EOF
```
**Add Cordova Push plugin**
```bash
$ cordova plugin add aerogear-cordova-push
Adding aerogear-cordova-push to package.json
Saved plugin info for "aerogear-cordova-push" to config.xml
```

**Add Cordova Android platform**
```bash
$ cordova platform add android
Using cordova-fetch for cordova-android@~7.1.1
Adding android project...
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: org.aerogear.playground
	Name: HelloCordova
	Activity: MainActivity
	Android target: android-27
Android project created with cordova-android@7.1.4
Android Studio project detected
Android Studio project detected
Installing "aerogear-cordova-push" for android
Installing "es6-promise-plugin" for android
Subproject Path: CordovaLib
Subproject Path: app

      Add an alpha and transparent notification icon into platforms/android/res/drawable folder to show correctly in Android Lollipop and above. The icon name should be icon_white.png

Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for android
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving android@~7.1.4 into config.xml file ...
```

**Comment by danielpassos** [comment] 2019-11-01 14:07
I'm going to close it since I could not reproduce it, feel free to reopen if you still having this problem

**Closed by danielpassos** 2019-11-01 14:07 UTC
